import 'package:myapp/tdlib/src/api/base_classes.dart';

import 'objects.dart';
import 'package:reflectable/reflectable.dart';

class Reflector extends Reflectable {
  const Reflector()
      : super(typeCapability, instanceInvokeCapability, newInstanceCapability);
}

const reflector = Reflector();

/// Attempts to parse an object as a [TdObject], or else returns the object
/// as is
dynamic tryConvertToTdObject(dynamic obj) {
  if (obj is Map) {
    return obj.containsKey('@type')
        ? (reflector.reflectType(classIndex[obj['@type']] ?? TdObject)
                as ClassMirror)
            .newInstance('fromJson', [obj])
        : obj;
  }

  return obj;
}

const Map<String, Type> classIndex = {
  "error": Error,
  "ok": Ok,
  "tdlibParameters": TdlibParameters,
  "authenticationCodeTypeTelegramMessage":
      AuthenticationCodeTypeTelegramMessage,
  "authenticationCodeTypeSms": AuthenticationCodeTypeSms,
  "authenticationCodeTypeCall": AuthenticationCodeTypeCall,
  "authenticationCodeTypeFlashCall": AuthenticationCodeTypeFlashCall,
  "authenticationCodeInfo": AuthenticationCodeInfo,
  "emailAddressAuthenticationCodeInfo": EmailAddressAuthenticationCodeInfo,
  "textEntity": TextEntity,
  "textEntities": TextEntities,
  "formattedText": FormattedText,
  "termsOfService": TermsOfService,
  "authorizationStateWaitTdlibParameters":
      AuthorizationStateWaitTdlibParameters,
  "authorizationStateWaitEncryptionKey": AuthorizationStateWaitEncryptionKey,
  "authorizationStateWaitPhoneNumber": AuthorizationStateWaitPhoneNumber,
  "authorizationStateWaitCode": AuthorizationStateWaitCode,
  "authorizationStateWaitOtherDeviceConfirmation":
      AuthorizationStateWaitOtherDeviceConfirmation,
  "authorizationStateWaitRegistration": AuthorizationStateWaitRegistration,
  "authorizationStateWaitPassword": AuthorizationStateWaitPassword,
  "authorizationStateReady": AuthorizationStateReady,
  "authorizationStateLoggingOut": AuthorizationStateLoggingOut,
  "authorizationStateClosing": AuthorizationStateClosing,
  "authorizationStateClosed": AuthorizationStateClosed,
  "passwordState": PasswordState,
  "recoveryEmailAddress": RecoveryEmailAddress,
  "temporaryPasswordState": TemporaryPasswordState,
  "localFile": LocalFile,
  "remoteFile": RemoteFile,
  "file": File,
  "inputFileId": InputFileId,
  "inputFileRemote": InputFileRemote,
  "inputFileLocal": InputFileLocal,
  "inputFileGenerated": InputFileGenerated,
  "photoSize": PhotoSize,
  "minithumbnail": Minithumbnail,
  "thumbnailFormatJpeg": ThumbnailFormatJpeg,
  "thumbnailFormatPng": ThumbnailFormatPng,
  "thumbnailFormatWebp": ThumbnailFormatWebp,
  "thumbnailFormatGif": ThumbnailFormatGif,
  "thumbnailFormatTgs": ThumbnailFormatTgs,
  "thumbnailFormatMpeg4": ThumbnailFormatMpeg4,
  "thumbnail": Thumbnail,
  "maskPointForehead": MaskPointForehead,
  "maskPointEyes": MaskPointEyes,
  "maskPointMouth": MaskPointMouth,
  "maskPointChin": MaskPointChin,
  "maskPosition": MaskPosition,
  "closedVectorPath": ClosedVectorPath,
  "pollOption": PollOption,
  "pollTypeRegular": PollTypeRegular,
  "pollTypeQuiz": PollTypeQuiz,
  "animation": Animation,
  "audio": Audio,
  "document": Document,
  "photo": Photo,
  "sticker": Sticker,
  "video": Video,
  "videoNote": VideoNote,
  "voiceNote": VoiceNote,
  "contact": Contact,
  "location": Location,
  "venue": Venue,
  "game": Game,
  "poll": Poll,
  "profilePhoto": ProfilePhoto,
  "chatPhotoInfo": ChatPhotoInfo,
  "userTypeRegular": UserTypeRegular,
  "userTypeDeleted": UserTypeDeleted,
  "userTypeBot": UserTypeBot,
  "userTypeUnknown": UserTypeUnknown,
  "botCommand": BotCommand,
  "botCommands": BotCommands,
  "chatLocation": ChatLocation,
  "animatedChatPhoto": AnimatedChatPhoto,
  "chatPhoto": ChatPhoto,
  "chatPhotos": ChatPhotos,
  "inputChatPhotoPrevious": InputChatPhotoPrevious,
  "inputChatPhotoStatic": InputChatPhotoStatic,
  "inputChatPhotoAnimation": InputChatPhotoAnimation,
  "user": User,
  "userFullInfo": UserFullInfo,
  "users": Users,
  "chatAdministrator": ChatAdministrator,
  "chatAdministrators": ChatAdministrators,
  "chatPermissions": ChatPermissions,
  "chatMemberStatusCreator": ChatMemberStatusCreator,
  "chatMemberStatusAdministrator": ChatMemberStatusAdministrator,
  "chatMemberStatusMember": ChatMemberStatusMember,
  "chatMemberStatusRestricted": ChatMemberStatusRestricted,
  "chatMemberStatusLeft": ChatMemberStatusLeft,
  "chatMemberStatusBanned": ChatMemberStatusBanned,
  "chatMember": ChatMember,
  "chatMembers": ChatMembers,
  "chatMembersFilterContacts": ChatMembersFilterContacts,
  "chatMembersFilterAdministrators": ChatMembersFilterAdministrators,
  "chatMembersFilterMembers": ChatMembersFilterMembers,
  "chatMembersFilterMention": ChatMembersFilterMention,
  "chatMembersFilterRestricted": ChatMembersFilterRestricted,
  "chatMembersFilterBanned": ChatMembersFilterBanned,
  "chatMembersFilterBots": ChatMembersFilterBots,
  "supergroupMembersFilterRecent": SupergroupMembersFilterRecent,
  "supergroupMembersFilterContacts": SupergroupMembersFilterContacts,
  "supergroupMembersFilterAdministrators":
      SupergroupMembersFilterAdministrators,
  "supergroupMembersFilterSearch": SupergroupMembersFilterSearch,
  "supergroupMembersFilterRestricted": SupergroupMembersFilterRestricted,
  "supergroupMembersFilterBanned": SupergroupMembersFilterBanned,
  "supergroupMembersFilterMention": SupergroupMembersFilterMention,
  "supergroupMembersFilterBots": SupergroupMembersFilterBots,
  "chatInviteLink": ChatInviteLink,
  "chatInviteLinks": ChatInviteLinks,
  "chatInviteLinkCount": ChatInviteLinkCount,
  "chatInviteLinkCounts": ChatInviteLinkCounts,
  "chatInviteLinkMember": ChatInviteLinkMember,
  "chatInviteLinkMembers": ChatInviteLinkMembers,
  "chatInviteLinkInfo": ChatInviteLinkInfo,
  "basicGroup": BasicGroup,
  "basicGroupFullInfo": BasicGroupFullInfo,
  "supergroup": Supergroup,
  "supergroupFullInfo": SupergroupFullInfo,
  "secretChatStatePending": SecretChatStatePending,
  "secretChatStateReady": SecretChatStateReady,
  "secretChatStateClosed": SecretChatStateClosed,
  "secretChat": SecretChat,
  "messageSenderUser": MessageSenderUser,
  "messageSenderChat": MessageSenderChat,
  "messageSenders": MessageSenders,
  "messageForwardOriginUser": MessageForwardOriginUser,
  "messageForwardOriginChat": MessageForwardOriginChat,
  "messageForwardOriginHiddenUser": MessageForwardOriginHiddenUser,
  "messageForwardOriginChannel": MessageForwardOriginChannel,
  "messageForwardOriginMessageImport": MessageForwardOriginMessageImport,
  "messageForwardInfo": MessageForwardInfo,
  "messageReplyInfo": MessageReplyInfo,
  "messageInteractionInfo": MessageInteractionInfo,
  "messageSendingStatePending": MessageSendingStatePending,
  "messageSendingStateFailed": MessageSendingStateFailed,
  "message": Message,
  "messages": Messages,
  "foundMessages": FoundMessages,
  "sponsoredMessage": SponsoredMessage,
  "sponsoredMessages": SponsoredMessages,
  "notificationSettingsScopePrivateChats":
      NotificationSettingsScopePrivateChats,
  "notificationSettingsScopeGroupChats": NotificationSettingsScopeGroupChats,
  "notificationSettingsScopeChannelChats":
      NotificationSettingsScopeChannelChats,
  "chatNotificationSettings": ChatNotificationSettings,
  "scopeNotificationSettings": ScopeNotificationSettings,
  "draftMessage": DraftMessage,
  "chatTypePrivate": ChatTypePrivate,
  "chatTypeBasicGroup": ChatTypeBasicGroup,
  "chatTypeSupergroup": ChatTypeSupergroup,
  "chatTypeSecret": ChatTypeSecret,
  "chatFilter": ChatFilter,
  "chatFilterInfo": ChatFilterInfo,
  "recommendedChatFilter": RecommendedChatFilter,
  "recommendedChatFilters": RecommendedChatFilters,
  "chatListMain": ChatListMain,
  "chatListArchive": ChatListArchive,
  "chatListFilter": ChatListFilter,
  "chatLists": ChatLists,
  "chatSourceMtprotoProxy": ChatSourceMtprotoProxy,
  "chatSourcePublicServiceAnnouncement": ChatSourcePublicServiceAnnouncement,
  "chatPosition": ChatPosition,
  "voiceChat": VoiceChat,
  "chat": Chat,
  "chats": Chats,
  "chatNearby": ChatNearby,
  "chatsNearby": ChatsNearby,
  "publicChatTypeHasUsername": PublicChatTypeHasUsername,
  "publicChatTypeIsLocationBased": PublicChatTypeIsLocationBased,
  "chatActionBarReportSpam": ChatActionBarReportSpam,
  "chatActionBarReportUnrelatedLocation": ChatActionBarReportUnrelatedLocation,
  "chatActionBarInviteMembers": ChatActionBarInviteMembers,
  "chatActionBarReportAddBlock": ChatActionBarReportAddBlock,
  "chatActionBarAddContact": ChatActionBarAddContact,
  "chatActionBarSharePhoneNumber": ChatActionBarSharePhoneNumber,
  "keyboardButtonTypeText": KeyboardButtonTypeText,
  "keyboardButtonTypeRequestPhoneNumber": KeyboardButtonTypeRequestPhoneNumber,
  "keyboardButtonTypeRequestLocation": KeyboardButtonTypeRequestLocation,
  "keyboardButtonTypeRequestPoll": KeyboardButtonTypeRequestPoll,
  "keyboardButton": KeyboardButton,
  "inlineKeyboardButtonTypeUrl": InlineKeyboardButtonTypeUrl,
  "inlineKeyboardButtonTypeLoginUrl": InlineKeyboardButtonTypeLoginUrl,
  "inlineKeyboardButtonTypeCallback": InlineKeyboardButtonTypeCallback,
  "inlineKeyboardButtonTypeCallbackWithPassword":
      InlineKeyboardButtonTypeCallbackWithPassword,
  "inlineKeyboardButtonTypeCallbackGame": InlineKeyboardButtonTypeCallbackGame,
  "inlineKeyboardButtonTypeSwitchInline": InlineKeyboardButtonTypeSwitchInline,
  "inlineKeyboardButtonTypeBuy": InlineKeyboardButtonTypeBuy,
  "inlineKeyboardButton": InlineKeyboardButton,
  "replyMarkupRemoveKeyboard": ReplyMarkupRemoveKeyboard,
  "replyMarkupForceReply": ReplyMarkupForceReply,
  "replyMarkupShowKeyboard": ReplyMarkupShowKeyboard,
  "replyMarkupInlineKeyboard": ReplyMarkupInlineKeyboard,
  "loginUrlInfoOpen": LoginUrlInfoOpen,
  "loginUrlInfoRequestConfirmation": LoginUrlInfoRequestConfirmation,
  "messageThreadInfo": MessageThreadInfo,
  "richTextPlain": RichTextPlain,
  "richTextBold": RichTextBold,
  "richTextItalic": RichTextItalic,
  "richTextUnderline": RichTextUnderline,
  "richTextStrikethrough": RichTextStrikethrough,
  "richTextFixed": RichTextFixed,
  "richTextUrl": RichTextUrl,
  "richTextEmailAddress": RichTextEmailAddress,
  "richTextSubscript": RichTextSubscript,
  "richTextSuperscript": RichTextSuperscript,
  "richTextMarked": RichTextMarked,
  "richTextPhoneNumber": RichTextPhoneNumber,
  "richTextIcon": RichTextIcon,
  "richTextReference": RichTextReference,
  "richTextAnchor": RichTextAnchor,
  "richTextAnchorLink": RichTextAnchorLink,
  "richTexts": RichTexts,
  "pageBlockCaption": PageBlockCaption,
  "pageBlockListItem": PageBlockListItem,
  "pageBlockHorizontalAlignmentLeft": PageBlockHorizontalAlignmentLeft,
  "pageBlockHorizontalAlignmentCenter": PageBlockHorizontalAlignmentCenter,
  "pageBlockHorizontalAlignmentRight": PageBlockHorizontalAlignmentRight,
  "pageBlockVerticalAlignmentTop": PageBlockVerticalAlignmentTop,
  "pageBlockVerticalAlignmentMiddle": PageBlockVerticalAlignmentMiddle,
  "pageBlockVerticalAlignmentBottom": PageBlockVerticalAlignmentBottom,
  "pageBlockTableCell": PageBlockTableCell,
  "pageBlockRelatedArticle": PageBlockRelatedArticle,
  "pageBlockTitle": PageBlockTitle,
  "pageBlockSubtitle": PageBlockSubtitle,
  "pageBlockAuthorDate": PageBlockAuthorDate,
  "pageBlockHeader": PageBlockHeader,
  "pageBlockSubheader": PageBlockSubheader,
  "pageBlockKicker": PageBlockKicker,
  "pageBlockParagraph": PageBlockParagraph,
  "pageBlockPreformatted": PageBlockPreformatted,
  "pageBlockFooter": PageBlockFooter,
  "pageBlockDivider": PageBlockDivider,
  "pageBlockAnchor": PageBlockAnchor,
  "pageBlockList": PageBlockList,
  "pageBlockBlockQuote": PageBlockBlockQuote,
  "pageBlockPullQuote": PageBlockPullQuote,
  "pageBlockAnimation": PageBlockAnimation,
  "pageBlockAudio": PageBlockAudio,
  "pageBlockPhoto": PageBlockPhoto,
  "pageBlockVideo": PageBlockVideo,
  "pageBlockVoiceNote": PageBlockVoiceNote,
  "pageBlockCover": PageBlockCover,
  "pageBlockEmbedded": PageBlockEmbedded,
  "pageBlockEmbeddedPost": PageBlockEmbeddedPost,
  "pageBlockCollage": PageBlockCollage,
  "pageBlockSlideshow": PageBlockSlideshow,
  "pageBlockChatLink": PageBlockChatLink,
  "pageBlockTable": PageBlockTable,
  "pageBlockDetails": PageBlockDetails,
  "pageBlockRelatedArticles": PageBlockRelatedArticles,
  "pageBlockMap": PageBlockMap,
  "webPageInstantView": WebPageInstantView,
  "webPage": WebPage,
  "countryInfo": CountryInfo,
  "countries": Countries,
  "phoneNumberInfo": PhoneNumberInfo,
  "bankCardActionOpenUrl": BankCardActionOpenUrl,
  "bankCardInfo": BankCardInfo,
  "address": Address,
  "labeledPricePart": LabeledPricePart,
  "invoice": Invoice,
  "orderInfo": OrderInfo,
  "shippingOption": ShippingOption,
  "savedCredentials": SavedCredentials,
  "inputCredentialsSaved": InputCredentialsSaved,
  "inputCredentialsNew": InputCredentialsNew,
  "inputCredentialsApplePay": InputCredentialsApplePay,
  "inputCredentialsGooglePay": InputCredentialsGooglePay,
  "paymentsProviderStripe": PaymentsProviderStripe,
  "paymentFormTheme": PaymentFormTheme,
  "paymentForm": PaymentForm,
  "validatedOrderInfo": ValidatedOrderInfo,
  "paymentResult": PaymentResult,
  "paymentReceipt": PaymentReceipt,
  "datedFile": DatedFile,
  "passportElementTypePersonalDetails": PassportElementTypePersonalDetails,
  "passportElementTypePassport": PassportElementTypePassport,
  "passportElementTypeDriverLicense": PassportElementTypeDriverLicense,
  "passportElementTypeIdentityCard": PassportElementTypeIdentityCard,
  "passportElementTypeInternalPassport": PassportElementTypeInternalPassport,
  "passportElementTypeAddress": PassportElementTypeAddress,
  "passportElementTypeUtilityBill": PassportElementTypeUtilityBill,
  "passportElementTypeBankStatement": PassportElementTypeBankStatement,
  "passportElementTypeRentalAgreement": PassportElementTypeRentalAgreement,
  "passportElementTypePassportRegistration":
      PassportElementTypePassportRegistration,
  "passportElementTypeTemporaryRegistration":
      PassportElementTypeTemporaryRegistration,
  "passportElementTypePhoneNumber": PassportElementTypePhoneNumber,
  "passportElementTypeEmailAddress": PassportElementTypeEmailAddress,
  "date": Date,
  "personalDetails": PersonalDetails,
  "identityDocument": IdentityDocument,
  "inputIdentityDocument": InputIdentityDocument,
  "personalDocument": PersonalDocument,
  "inputPersonalDocument": InputPersonalDocument,
  "passportElementPersonalDetails": PassportElementPersonalDetails,
  "passportElementPassport": PassportElementPassport,
  "passportElementDriverLicense": PassportElementDriverLicense,
  "passportElementIdentityCard": PassportElementIdentityCard,
  "passportElementInternalPassport": PassportElementInternalPassport,
  "passportElementAddress": PassportElementAddress,
  "passportElementUtilityBill": PassportElementUtilityBill,
  "passportElementBankStatement": PassportElementBankStatement,
  "passportElementRentalAgreement": PassportElementRentalAgreement,
  "passportElementPassportRegistration": PassportElementPassportRegistration,
  "passportElementTemporaryRegistration": PassportElementTemporaryRegistration,
  "passportElementPhoneNumber": PassportElementPhoneNumber,
  "passportElementEmailAddress": PassportElementEmailAddress,
  "inputPassportElementPersonalDetails": InputPassportElementPersonalDetails,
  "inputPassportElementPassport": InputPassportElementPassport,
  "inputPassportElementDriverLicense": InputPassportElementDriverLicense,
  "inputPassportElementIdentityCard": InputPassportElementIdentityCard,
  "inputPassportElementInternalPassport": InputPassportElementInternalPassport,
  "inputPassportElementAddress": InputPassportElementAddress,
  "inputPassportElementUtilityBill": InputPassportElementUtilityBill,
  "inputPassportElementBankStatement": InputPassportElementBankStatement,
  "inputPassportElementRentalAgreement": InputPassportElementRentalAgreement,
  "inputPassportElementPassportRegistration":
      InputPassportElementPassportRegistration,
  "inputPassportElementTemporaryRegistration":
      InputPassportElementTemporaryRegistration,
  "inputPassportElementPhoneNumber": InputPassportElementPhoneNumber,
  "inputPassportElementEmailAddress": InputPassportElementEmailAddress,
  "passportElements": PassportElements,
  "passportElementErrorSourceUnspecified":
      PassportElementErrorSourceUnspecified,
  "passportElementErrorSourceDataField": PassportElementErrorSourceDataField,
  "passportElementErrorSourceFrontSide": PassportElementErrorSourceFrontSide,
  "passportElementErrorSourceReverseSide":
      PassportElementErrorSourceReverseSide,
  "passportElementErrorSourceSelfie": PassportElementErrorSourceSelfie,
  "passportElementErrorSourceTranslationFile":
      PassportElementErrorSourceTranslationFile,
  "passportElementErrorSourceTranslationFiles":
      PassportElementErrorSourceTranslationFiles,
  "passportElementErrorSourceFile": PassportElementErrorSourceFile,
  "passportElementErrorSourceFiles": PassportElementErrorSourceFiles,
  "passportElementError": PassportElementError,
  "passportSuitableElement": PassportSuitableElement,
  "passportRequiredElement": PassportRequiredElement,
  "passportAuthorizationForm": PassportAuthorizationForm,
  "passportElementsWithErrors": PassportElementsWithErrors,
  "encryptedCredentials": EncryptedCredentials,
  "encryptedPassportElement": EncryptedPassportElement,
  "inputPassportElementErrorSourceUnspecified":
      InputPassportElementErrorSourceUnspecified,
  "inputPassportElementErrorSourceDataField":
      InputPassportElementErrorSourceDataField,
  "inputPassportElementErrorSourceFrontSide":
      InputPassportElementErrorSourceFrontSide,
  "inputPassportElementErrorSourceReverseSide":
      InputPassportElementErrorSourceReverseSide,
  "inputPassportElementErrorSourceSelfie":
      InputPassportElementErrorSourceSelfie,
  "inputPassportElementErrorSourceTranslationFile":
      InputPassportElementErrorSourceTranslationFile,
  "inputPassportElementErrorSourceTranslationFiles":
      InputPassportElementErrorSourceTranslationFiles,
  "inputPassportElementErrorSourceFile": InputPassportElementErrorSourceFile,
  "inputPassportElementErrorSourceFiles": InputPassportElementErrorSourceFiles,
  "inputPassportElementError": InputPassportElementError,
  "messageText": MessageText,
  "messageAnimation": MessageAnimation,
  "messageAudio": MessageAudio,
  "messageDocument": MessageDocument,
  "messagePhoto": MessagePhoto,
  "messageExpiredPhoto": MessageExpiredPhoto,
  "messageSticker": MessageSticker,
  "messageVideo": MessageVideo,
  "messageExpiredVideo": MessageExpiredVideo,
  "messageVideoNote": MessageVideoNote,
  "messageVoiceNote": MessageVoiceNote,
  "messageLocation": MessageLocation,
  "messageVenue": MessageVenue,
  "messageContact": MessageContact,
  "messageDice": MessageDice,
  "messageGame": MessageGame,
  "messagePoll": MessagePoll,
  "messageInvoice": MessageInvoice,
  "messageCall": MessageCall,
  "messageVoiceChatScheduled": MessageVoiceChatScheduled,
  "messageVoiceChatStarted": MessageVoiceChatStarted,
  "messageVoiceChatEnded": MessageVoiceChatEnded,
  "messageInviteVoiceChatParticipants": MessageInviteVoiceChatParticipants,
  "messageBasicGroupChatCreate": MessageBasicGroupChatCreate,
  "messageSupergroupChatCreate": MessageSupergroupChatCreate,
  "messageChatChangeTitle": MessageChatChangeTitle,
  "messageChatChangePhoto": MessageChatChangePhoto,
  "messageChatDeletePhoto": MessageChatDeletePhoto,
  "messageChatAddMembers": MessageChatAddMembers,
  "messageChatJoinByLink": MessageChatJoinByLink,
  "messageChatDeleteMember": MessageChatDeleteMember,
  "messageChatUpgradeTo": MessageChatUpgradeTo,
  "messageChatUpgradeFrom": MessageChatUpgradeFrom,
  "messagePinMessage": MessagePinMessage,
  "messageScreenshotTaken": MessageScreenshotTaken,
  "messageChatSetTheme": MessageChatSetTheme,
  "messageChatSetTtl": MessageChatSetTtl,
  "messageCustomServiceAction": MessageCustomServiceAction,
  "messageGameScore": MessageGameScore,
  "messagePaymentSuccessful": MessagePaymentSuccessful,
  "messagePaymentSuccessfulBot": MessagePaymentSuccessfulBot,
  "messageContactRegistered": MessageContactRegistered,
  "messageWebsiteConnected": MessageWebsiteConnected,
  "messagePassportDataSent": MessagePassportDataSent,
  "messagePassportDataReceived": MessagePassportDataReceived,
  "messageProximityAlertTriggered": MessageProximityAlertTriggered,
  "messageUnsupported": MessageUnsupported,
  "textEntityTypeMention": TextEntityTypeMention,
  "textEntityTypeHashtag": TextEntityTypeHashtag,
  "textEntityTypeCashtag": TextEntityTypeCashtag,
  "textEntityTypeBotCommand": TextEntityTypeBotCommand,
  "textEntityTypeUrl": TextEntityTypeUrl,
  "textEntityTypeEmailAddress": TextEntityTypeEmailAddress,
  "textEntityTypePhoneNumber": TextEntityTypePhoneNumber,
  "textEntityTypeBankCardNumber": TextEntityTypeBankCardNumber,
  "textEntityTypeBold": TextEntityTypeBold,
  "textEntityTypeItalic": TextEntityTypeItalic,
  "textEntityTypeUnderline": TextEntityTypeUnderline,
  "textEntityTypeStrikethrough": TextEntityTypeStrikethrough,
  "textEntityTypeCode": TextEntityTypeCode,
  "textEntityTypePre": TextEntityTypePre,
  "textEntityTypePreCode": TextEntityTypePreCode,
  "textEntityTypeTextUrl": TextEntityTypeTextUrl,
  "textEntityTypeMentionName": TextEntityTypeMentionName,
  "textEntityTypeMediaTimestamp": TextEntityTypeMediaTimestamp,
  "inputThumbnail": InputThumbnail,
  "messageSchedulingStateSendAtDate": MessageSchedulingStateSendAtDate,
  "messageSchedulingStateSendWhenOnline": MessageSchedulingStateSendWhenOnline,
  "messageSendOptions": MessageSendOptions,
  "messageCopyOptions": MessageCopyOptions,
  "inputMessageText": InputMessageText,
  "inputMessageAnimation": InputMessageAnimation,
  "inputMessageAudio": InputMessageAudio,
  "inputMessageDocument": InputMessageDocument,
  "inputMessagePhoto": InputMessagePhoto,
  "inputMessageSticker": InputMessageSticker,
  "inputMessageVideo": InputMessageVideo,
  "inputMessageVideoNote": InputMessageVideoNote,
  "inputMessageVoiceNote": InputMessageVoiceNote,
  "inputMessageLocation": InputMessageLocation,
  "inputMessageVenue": InputMessageVenue,
  "inputMessageContact": InputMessageContact,
  "inputMessageDice": InputMessageDice,
  "inputMessageGame": InputMessageGame,
  "inputMessageInvoice": InputMessageInvoice,
  "inputMessagePoll": InputMessagePoll,
  "inputMessageForwarded": InputMessageForwarded,
  "searchMessagesFilterEmpty": SearchMessagesFilterEmpty,
  "searchMessagesFilterAnimation": SearchMessagesFilterAnimation,
  "searchMessagesFilterAudio": SearchMessagesFilterAudio,
  "searchMessagesFilterDocument": SearchMessagesFilterDocument,
  "searchMessagesFilterPhoto": SearchMessagesFilterPhoto,
  "searchMessagesFilterVideo": SearchMessagesFilterVideo,
  "searchMessagesFilterVoiceNote": SearchMessagesFilterVoiceNote,
  "searchMessagesFilterPhotoAndVideo": SearchMessagesFilterPhotoAndVideo,
  "searchMessagesFilterUrl": SearchMessagesFilterUrl,
  "searchMessagesFilterChatPhoto": SearchMessagesFilterChatPhoto,
  "searchMessagesFilterCall": SearchMessagesFilterCall,
  "searchMessagesFilterMissedCall": SearchMessagesFilterMissedCall,
  "searchMessagesFilterVideoNote": SearchMessagesFilterVideoNote,
  "searchMessagesFilterVoiceAndVideoNote":
      SearchMessagesFilterVoiceAndVideoNote,
  "searchMessagesFilterMention": SearchMessagesFilterMention,
  "searchMessagesFilterUnreadMention": SearchMessagesFilterUnreadMention,
  "searchMessagesFilterFailedToSend": SearchMessagesFilterFailedToSend,
  "searchMessagesFilterPinned": SearchMessagesFilterPinned,
  "chatActionTyping": ChatActionTyping,
  "chatActionRecordingVideo": ChatActionRecordingVideo,
  "chatActionUploadingVideo": ChatActionUploadingVideo,
  "chatActionRecordingVoiceNote": ChatActionRecordingVoiceNote,
  "chatActionUploadingVoiceNote": ChatActionUploadingVoiceNote,
  "chatActionUploadingPhoto": ChatActionUploadingPhoto,
  "chatActionUploadingDocument": ChatActionUploadingDocument,
  "chatActionChoosingSticker": ChatActionChoosingSticker,
  "chatActionChoosingLocation": ChatActionChoosingLocation,
  "chatActionChoosingContact": ChatActionChoosingContact,
  "chatActionStartPlayingGame": ChatActionStartPlayingGame,
  "chatActionRecordingVideoNote": ChatActionRecordingVideoNote,
  "chatActionUploadingVideoNote": ChatActionUploadingVideoNote,
  "chatActionWatchingAnimations": ChatActionWatchingAnimations,
  "chatActionCancel": ChatActionCancel,
  "userStatusEmpty": UserStatusEmpty,
  "userStatusOnline": UserStatusOnline,
  "userStatusOffline": UserStatusOffline,
  "userStatusRecently": UserStatusRecently,
  "userStatusLastWeek": UserStatusLastWeek,
  "userStatusLastMonth": UserStatusLastMonth,
  "stickers": Stickers,
  "emojis": Emojis,
  "stickerSet": StickerSet,
  "stickerSetInfo": StickerSetInfo,
  "stickerSets": StickerSets,
  "callDiscardReasonEmpty": CallDiscardReasonEmpty,
  "callDiscardReasonMissed": CallDiscardReasonMissed,
  "callDiscardReasonDeclined": CallDiscardReasonDeclined,
  "callDiscardReasonDisconnected": CallDiscardReasonDisconnected,
  "callDiscardReasonHungUp": CallDiscardReasonHungUp,
  "callProtocol": CallProtocol,
  "callServerTypeTelegramReflector": CallServerTypeTelegramReflector,
  "callServerTypeWebrtc": CallServerTypeWebrtc,
  "callServer": CallServer,
  "callId": CallId,
  "groupCallId": GroupCallId,
  "callStatePending": CallStatePending,
  "callStateExchangingKeys": CallStateExchangingKeys,
  "callStateReady": CallStateReady,
  "callStateHangingUp": CallStateHangingUp,
  "callStateDiscarded": CallStateDiscarded,
  "callStateError": CallStateError,
  "groupCallVideoQualityThumbnail": GroupCallVideoQualityThumbnail,
  "groupCallVideoQualityMedium": GroupCallVideoQualityMedium,
  "groupCallVideoQualityFull": GroupCallVideoQualityFull,
  "groupCallRecentSpeaker": GroupCallRecentSpeaker,
  "groupCall": GroupCall,
  "groupCallVideoSourceGroup": GroupCallVideoSourceGroup,
  "groupCallParticipantVideoInfo": GroupCallParticipantVideoInfo,
  "groupCallParticipant": GroupCallParticipant,
  "callProblemEcho": CallProblemEcho,
  "callProblemNoise": CallProblemNoise,
  "callProblemInterruptions": CallProblemInterruptions,
  "callProblemDistortedSpeech": CallProblemDistortedSpeech,
  "callProblemSilentLocal": CallProblemSilentLocal,
  "callProblemSilentRemote": CallProblemSilentRemote,
  "callProblemDropped": CallProblemDropped,
  "callProblemDistortedVideo": CallProblemDistortedVideo,
  "callProblemPixelatedVideo": CallProblemPixelatedVideo,
  "call": Call,
  "phoneNumberAuthenticationSettings": PhoneNumberAuthenticationSettings,
  "animations": Animations,
  "diceStickersRegular": DiceStickersRegular,
  "diceStickersSlotMachine": DiceStickersSlotMachine,
  "importedContacts": ImportedContacts,
  "httpUrl": HttpUrl,
  "inputInlineQueryResultAnimation": InputInlineQueryResultAnimation,
  "inputInlineQueryResultArticle": InputInlineQueryResultArticle,
  "inputInlineQueryResultAudio": InputInlineQueryResultAudio,
  "inputInlineQueryResultContact": InputInlineQueryResultContact,
  "inputInlineQueryResultDocument": InputInlineQueryResultDocument,
  "inputInlineQueryResultGame": InputInlineQueryResultGame,
  "inputInlineQueryResultLocation": InputInlineQueryResultLocation,
  "inputInlineQueryResultPhoto": InputInlineQueryResultPhoto,
  "inputInlineQueryResultSticker": InputInlineQueryResultSticker,
  "inputInlineQueryResultVenue": InputInlineQueryResultVenue,
  "inputInlineQueryResultVideo": InputInlineQueryResultVideo,
  "inputInlineQueryResultVoiceNote": InputInlineQueryResultVoiceNote,
  "inlineQueryResultArticle": InlineQueryResultArticle,
  "inlineQueryResultContact": InlineQueryResultContact,
  "inlineQueryResultLocation": InlineQueryResultLocation,
  "inlineQueryResultVenue": InlineQueryResultVenue,
  "inlineQueryResultGame": InlineQueryResultGame,
  "inlineQueryResultAnimation": InlineQueryResultAnimation,
  "inlineQueryResultAudio": InlineQueryResultAudio,
  "inlineQueryResultDocument": InlineQueryResultDocument,
  "inlineQueryResultPhoto": InlineQueryResultPhoto,
  "inlineQueryResultSticker": InlineQueryResultSticker,
  "inlineQueryResultVideo": InlineQueryResultVideo,
  "inlineQueryResultVoiceNote": InlineQueryResultVoiceNote,
  "inlineQueryResults": InlineQueryResults,
  "callbackQueryPayloadData": CallbackQueryPayloadData,
  "callbackQueryPayloadDataWithPassword": CallbackQueryPayloadDataWithPassword,
  "callbackQueryPayloadGame": CallbackQueryPayloadGame,
  "callbackQueryAnswer": CallbackQueryAnswer,
  "customRequestResult": CustomRequestResult,
  "gameHighScore": GameHighScore,
  "gameHighScores": GameHighScores,
  "chatEventMessageEdited": ChatEventMessageEdited,
  "chatEventMessageDeleted": ChatEventMessageDeleted,
  "chatEventPollStopped": ChatEventPollStopped,
  "chatEventMessagePinned": ChatEventMessagePinned,
  "chatEventMessageUnpinned": ChatEventMessageUnpinned,
  "chatEventMemberJoined": ChatEventMemberJoined,
  "chatEventMemberJoinedByInviteLink": ChatEventMemberJoinedByInviteLink,
  "chatEventMemberLeft": ChatEventMemberLeft,
  "chatEventMemberInvited": ChatEventMemberInvited,
  "chatEventMemberPromoted": ChatEventMemberPromoted,
  "chatEventMemberRestricted": ChatEventMemberRestricted,
  "chatEventTitleChanged": ChatEventTitleChanged,
  "chatEventPermissionsChanged": ChatEventPermissionsChanged,
  "chatEventDescriptionChanged": ChatEventDescriptionChanged,
  "chatEventUsernameChanged": ChatEventUsernameChanged,
  "chatEventPhotoChanged": ChatEventPhotoChanged,
  "chatEventInvitesToggled": ChatEventInvitesToggled,
  "chatEventLinkedChatChanged": ChatEventLinkedChatChanged,
  "chatEventSlowModeDelayChanged": ChatEventSlowModeDelayChanged,
  "chatEventMessageTtlSettingChanged": ChatEventMessageTtlSettingChanged,
  "chatEventSignMessagesToggled": ChatEventSignMessagesToggled,
  "chatEventStickerSetChanged": ChatEventStickerSetChanged,
  "chatEventLocationChanged": ChatEventLocationChanged,
  "chatEventIsAllHistoryAvailableToggled":
      ChatEventIsAllHistoryAvailableToggled,
  "chatEventInviteLinkEdited": ChatEventInviteLinkEdited,
  "chatEventInviteLinkRevoked": ChatEventInviteLinkRevoked,
  "chatEventInviteLinkDeleted": ChatEventInviteLinkDeleted,
  "chatEventVoiceChatCreated": ChatEventVoiceChatCreated,
  "chatEventVoiceChatDiscarded": ChatEventVoiceChatDiscarded,
  "chatEventVoiceChatParticipantIsMutedToggled":
      ChatEventVoiceChatParticipantIsMutedToggled,
  "chatEventVoiceChatParticipantVolumeLevelChanged":
      ChatEventVoiceChatParticipantVolumeLevelChanged,
  "chatEventVoiceChatMuteNewParticipantsToggled":
      ChatEventVoiceChatMuteNewParticipantsToggled,
  "chatEvent": ChatEvent,
  "chatEvents": ChatEvents,
  "chatEventLogFilters": ChatEventLogFilters,
  "languagePackStringValueOrdinary": LanguagePackStringValueOrdinary,
  "languagePackStringValuePluralized": LanguagePackStringValuePluralized,
  "languagePackStringValueDeleted": LanguagePackStringValueDeleted,
  "languagePackString": LanguagePackString,
  "languagePackStrings": LanguagePackStrings,
  "languagePackInfo": LanguagePackInfo,
  "localizationTargetInfo": LocalizationTargetInfo,
  "deviceTokenFirebaseCloudMessaging": DeviceTokenFirebaseCloudMessaging,
  "deviceTokenApplePush": DeviceTokenApplePush,
  "deviceTokenApplePushVoIP": DeviceTokenApplePushVoIP,
  "deviceTokenWindowsPush": DeviceTokenWindowsPush,
  "deviceTokenMicrosoftPush": DeviceTokenMicrosoftPush,
  "deviceTokenMicrosoftPushVoIP": DeviceTokenMicrosoftPushVoIP,
  "deviceTokenWebPush": DeviceTokenWebPush,
  "deviceTokenSimplePush": DeviceTokenSimplePush,
  "deviceTokenUbuntuPush": DeviceTokenUbuntuPush,
  "deviceTokenBlackBerryPush": DeviceTokenBlackBerryPush,
  "deviceTokenTizenPush": DeviceTokenTizenPush,
  "pushReceiverId": PushReceiverId,
  "backgroundFillSolid": BackgroundFillSolid,
  "backgroundFillGradient": BackgroundFillGradient,
  "backgroundFillFreeformGradient": BackgroundFillFreeformGradient,
  "backgroundTypeWallpaper": BackgroundTypeWallpaper,
  "backgroundTypePattern": BackgroundTypePattern,
  "backgroundTypeFill": BackgroundTypeFill,
  "background": Background,
  "backgrounds": Backgrounds,
  "inputBackgroundLocal": InputBackgroundLocal,
  "inputBackgroundRemote": InputBackgroundRemote,
  "themeSettings": ThemeSettings,
  "chatTheme": ChatTheme,
  "hashtags": Hashtags,
  "canTransferOwnershipResultOk": CanTransferOwnershipResultOk,
  "canTransferOwnershipResultPasswordNeeded":
      CanTransferOwnershipResultPasswordNeeded,
  "canTransferOwnershipResultPasswordTooFresh":
      CanTransferOwnershipResultPasswordTooFresh,
  "canTransferOwnershipResultSessionTooFresh":
      CanTransferOwnershipResultSessionTooFresh,
  "checkChatUsernameResultOk": CheckChatUsernameResultOk,
  "checkChatUsernameResultUsernameInvalid":
      CheckChatUsernameResultUsernameInvalid,
  "checkChatUsernameResultUsernameOccupied":
      CheckChatUsernameResultUsernameOccupied,
  "checkChatUsernameResultPublicChatsTooMuch":
      CheckChatUsernameResultPublicChatsTooMuch,
  "checkChatUsernameResultPublicGroupsUnavailable":
      CheckChatUsernameResultPublicGroupsUnavailable,
  "checkStickerSetNameResultOk": CheckStickerSetNameResultOk,
  "checkStickerSetNameResultNameInvalid": CheckStickerSetNameResultNameInvalid,
  "checkStickerSetNameResultNameOccupied":
      CheckStickerSetNameResultNameOccupied,
  "resetPasswordResultOk": ResetPasswordResultOk,
  "resetPasswordResultPending": ResetPasswordResultPending,
  "resetPasswordResultDeclined": ResetPasswordResultDeclined,
  "messageFileTypePrivate": MessageFileTypePrivate,
  "messageFileTypeGroup": MessageFileTypeGroup,
  "messageFileTypeUnknown": MessageFileTypeUnknown,
  "pushMessageContentHidden": PushMessageContentHidden,
  "pushMessageContentAnimation": PushMessageContentAnimation,
  "pushMessageContentAudio": PushMessageContentAudio,
  "pushMessageContentContact": PushMessageContentContact,
  "pushMessageContentContactRegistered": PushMessageContentContactRegistered,
  "pushMessageContentDocument": PushMessageContentDocument,
  "pushMessageContentGame": PushMessageContentGame,
  "pushMessageContentGameScore": PushMessageContentGameScore,
  "pushMessageContentInvoice": PushMessageContentInvoice,
  "pushMessageContentLocation": PushMessageContentLocation,
  "pushMessageContentPhoto": PushMessageContentPhoto,
  "pushMessageContentPoll": PushMessageContentPoll,
  "pushMessageContentScreenshotTaken": PushMessageContentScreenshotTaken,
  "pushMessageContentSticker": PushMessageContentSticker,
  "pushMessageContentText": PushMessageContentText,
  "pushMessageContentVideo": PushMessageContentVideo,
  "pushMessageContentVideoNote": PushMessageContentVideoNote,
  "pushMessageContentVoiceNote": PushMessageContentVoiceNote,
  "pushMessageContentBasicGroupChatCreate":
      PushMessageContentBasicGroupChatCreate,
  "pushMessageContentChatAddMembers": PushMessageContentChatAddMembers,
  "pushMessageContentChatChangePhoto": PushMessageContentChatChangePhoto,
  "pushMessageContentChatChangeTitle": PushMessageContentChatChangeTitle,
  "pushMessageContentChatSetTheme": PushMessageContentChatSetTheme,
  "pushMessageContentChatDeleteMember": PushMessageContentChatDeleteMember,
  "pushMessageContentChatJoinByLink": PushMessageContentChatJoinByLink,
  "pushMessageContentMessageForwards": PushMessageContentMessageForwards,
  "pushMessageContentMediaAlbum": PushMessageContentMediaAlbum,
  "notificationTypeNewMessage": NotificationTypeNewMessage,
  "notificationTypeNewSecretChat": NotificationTypeNewSecretChat,
  "notificationTypeNewCall": NotificationTypeNewCall,
  "notificationTypeNewPushMessage": NotificationTypeNewPushMessage,
  "notificationGroupTypeMessages": NotificationGroupTypeMessages,
  "notificationGroupTypeMentions": NotificationGroupTypeMentions,
  "notificationGroupTypeSecretChat": NotificationGroupTypeSecretChat,
  "notificationGroupTypeCalls": NotificationGroupTypeCalls,
  "notification": Notification,
  "notificationGroup": NotificationGroup,
  "optionValueBoolean": OptionValueBoolean,
  "optionValueEmpty": OptionValueEmpty,
  "optionValueInteger": OptionValueInteger,
  "optionValueString": OptionValueString,
  "jsonObjectMember": JsonObjectMember,
  "jsonValueNull": JsonValueNull,
  "jsonValueBoolean": JsonValueBoolean,
  "jsonValueNumber": JsonValueNumber,
  "jsonValueString": JsonValueString,
  "jsonValueArray": JsonValueArray,
  "jsonValueObject": JsonValueObject,
  "userPrivacySettingRuleAllowAll": UserPrivacySettingRuleAllowAll,
  "userPrivacySettingRuleAllowContacts": UserPrivacySettingRuleAllowContacts,
  "userPrivacySettingRuleAllowUsers": UserPrivacySettingRuleAllowUsers,
  "userPrivacySettingRuleAllowChatMembers":
      UserPrivacySettingRuleAllowChatMembers,
  "userPrivacySettingRuleRestrictAll": UserPrivacySettingRuleRestrictAll,
  "userPrivacySettingRuleRestrictContacts":
      UserPrivacySettingRuleRestrictContacts,
  "userPrivacySettingRuleRestrictUsers": UserPrivacySettingRuleRestrictUsers,
  "userPrivacySettingRuleRestrictChatMembers":
      UserPrivacySettingRuleRestrictChatMembers,
  "userPrivacySettingRules": UserPrivacySettingRules,
  "userPrivacySettingShowStatus": UserPrivacySettingShowStatus,
  "userPrivacySettingShowProfilePhoto": UserPrivacySettingShowProfilePhoto,
  "userPrivacySettingShowLinkInForwardedMessages":
      UserPrivacySettingShowLinkInForwardedMessages,
  "userPrivacySettingShowPhoneNumber": UserPrivacySettingShowPhoneNumber,
  "userPrivacySettingAllowChatInvites": UserPrivacySettingAllowChatInvites,
  "userPrivacySettingAllowCalls": UserPrivacySettingAllowCalls,
  "userPrivacySettingAllowPeerToPeerCalls":
      UserPrivacySettingAllowPeerToPeerCalls,
  "userPrivacySettingAllowFindingByPhoneNumber":
      UserPrivacySettingAllowFindingByPhoneNumber,
  "accountTtl": AccountTtl,
  "session": Session,
  "sessions": Sessions,
  "connectedWebsite": ConnectedWebsite,
  "connectedWebsites": ConnectedWebsites,
  "chatReportReasonSpam": ChatReportReasonSpam,
  "chatReportReasonViolence": ChatReportReasonViolence,
  "chatReportReasonPornography": ChatReportReasonPornography,
  "chatReportReasonChildAbuse": ChatReportReasonChildAbuse,
  "chatReportReasonCopyright": ChatReportReasonCopyright,
  "chatReportReasonUnrelatedLocation": ChatReportReasonUnrelatedLocation,
  "chatReportReasonFake": ChatReportReasonFake,
  "chatReportReasonCustom": ChatReportReasonCustom,
  "internalLinkTypeActiveSessions": InternalLinkTypeActiveSessions,
  "internalLinkTypeAuthenticationCode": InternalLinkTypeAuthenticationCode,
  "internalLinkTypeBackground": InternalLinkTypeBackground,
  "internalLinkTypeBotStart": InternalLinkTypeBotStart,
  "internalLinkTypeBotStartInGroup": InternalLinkTypeBotStartInGroup,
  "internalLinkTypeChangePhoneNumber": InternalLinkTypeChangePhoneNumber,
  "internalLinkTypeChatInvite": InternalLinkTypeChatInvite,
  "internalLinkTypeFilterSettings": InternalLinkTypeFilterSettings,
  "internalLinkTypeGame": InternalLinkTypeGame,
  "internalLinkTypeLanguagePack": InternalLinkTypeLanguagePack,
  "internalLinkTypeMessage": InternalLinkTypeMessage,
  "internalLinkTypeMessageDraft": InternalLinkTypeMessageDraft,
  "internalLinkTypePassportDataRequest": InternalLinkTypePassportDataRequest,
  "internalLinkTypePhoneNumberConfirmation":
      InternalLinkTypePhoneNumberConfirmation,
  "internalLinkTypeProxy": InternalLinkTypeProxy,
  "internalLinkTypePublicChat": InternalLinkTypePublicChat,
  "internalLinkTypeQrCodeAuthentication": InternalLinkTypeQrCodeAuthentication,
  "internalLinkTypeSettings": InternalLinkTypeSettings,
  "internalLinkTypeStickerSet": InternalLinkTypeStickerSet,
  "internalLinkTypeTheme": InternalLinkTypeTheme,
  "internalLinkTypeThemeSettings": InternalLinkTypeThemeSettings,
  "internalLinkTypeUnknownDeepLink": InternalLinkTypeUnknownDeepLink,
  "internalLinkTypeVoiceChat": InternalLinkTypeVoiceChat,
  "messageLink": MessageLink,
  "messageLinkInfo": MessageLinkInfo,
  "filePart": FilePart,
  "fileTypeNone": FileTypeNone,
  "fileTypeAnimation": FileTypeAnimation,
  "fileTypeAudio": FileTypeAudio,
  "fileTypeDocument": FileTypeDocument,
  "fileTypePhoto": FileTypePhoto,
  "fileTypeProfilePhoto": FileTypeProfilePhoto,
  "fileTypeSecret": FileTypeSecret,
  "fileTypeSecretThumbnail": FileTypeSecretThumbnail,
  "fileTypeSecure": FileTypeSecure,
  "fileTypeSticker": FileTypeSticker,
  "fileTypeThumbnail": FileTypeThumbnail,
  "fileTypeUnknown": FileTypeUnknown,
  "fileTypeVideo": FileTypeVideo,
  "fileTypeVideoNote": FileTypeVideoNote,
  "fileTypeVoiceNote": FileTypeVoiceNote,
  "fileTypeWallpaper": FileTypeWallpaper,
  "storageStatisticsByFileType": StorageStatisticsByFileType,
  "storageStatisticsByChat": StorageStatisticsByChat,
  "storageStatistics": StorageStatistics,
  "storageStatisticsFast": StorageStatisticsFast,
  "databaseStatistics": DatabaseStatistics,
  "networkTypeNone": NetworkTypeNone,
  "networkTypeMobile": NetworkTypeMobile,
  "networkTypeMobileRoaming": NetworkTypeMobileRoaming,
  "networkTypeWiFi": NetworkTypeWiFi,
  "networkTypeOther": NetworkTypeOther,
  "networkStatisticsEntryFile": NetworkStatisticsEntryFile,
  "networkStatisticsEntryCall": NetworkStatisticsEntryCall,
  "networkStatistics": NetworkStatistics,
  "autoDownloadSettings": AutoDownloadSettings,
  "autoDownloadSettingsPresets": AutoDownloadSettingsPresets,
  "connectionStateWaitingForNetwork": ConnectionStateWaitingForNetwork,
  "connectionStateConnectingToProxy": ConnectionStateConnectingToProxy,
  "connectionStateConnecting": ConnectionStateConnecting,
  "connectionStateUpdating": ConnectionStateUpdating,
  "connectionStateReady": ConnectionStateReady,
  "topChatCategoryUsers": TopChatCategoryUsers,
  "topChatCategoryBots": TopChatCategoryBots,
  "topChatCategoryGroups": TopChatCategoryGroups,
  "topChatCategoryChannels": TopChatCategoryChannels,
  "topChatCategoryInlineBots": TopChatCategoryInlineBots,
  "topChatCategoryCalls": TopChatCategoryCalls,
  "topChatCategoryForwardChats": TopChatCategoryForwardChats,
  "tMeUrlTypeUser": TMeUrlTypeUser,
  "tMeUrlTypeSupergroup": TMeUrlTypeSupergroup,
  "tMeUrlTypeChatInvite": TMeUrlTypeChatInvite,
  "tMeUrlTypeStickerSet": TMeUrlTypeStickerSet,
  "tMeUrl": TMeUrl,
  "tMeUrls": TMeUrls,
  "suggestedActionEnableArchiveAndMuteNewChats":
      SuggestedActionEnableArchiveAndMuteNewChats,
  "suggestedActionCheckPassword": SuggestedActionCheckPassword,
  "suggestedActionCheckPhoneNumber": SuggestedActionCheckPhoneNumber,
  "suggestedActionSeeTicksHint": SuggestedActionSeeTicksHint,
  "suggestedActionConvertToBroadcastGroup":
      SuggestedActionConvertToBroadcastGroup,
  "count": Count,
  "text": Text,
  "seconds": Seconds,
  "deepLinkInfo": DeepLinkInfo,
  "textParseModeMarkdown": TextParseModeMarkdown,
  "textParseModeHTML": TextParseModeHTML,
  "proxyTypeSocks5": ProxyTypeSocks5,
  "proxyTypeHttp": ProxyTypeHttp,
  "proxyTypeMtproto": ProxyTypeMtproto,
  "proxy": Proxy,
  "proxies": Proxies,
  "inputStickerStatic": InputStickerStatic,
  "inputStickerAnimated": InputStickerAnimated,
  "dateRange": DateRange,
  "statisticalValue": StatisticalValue,
  "statisticalGraphData": StatisticalGraphData,
  "statisticalGraphAsync": StatisticalGraphAsync,
  "statisticalGraphError": StatisticalGraphError,
  "chatStatisticsMessageInteractionInfo": ChatStatisticsMessageInteractionInfo,
  "chatStatisticsMessageSenderInfo": ChatStatisticsMessageSenderInfo,
  "chatStatisticsAdministratorActionsInfo":
      ChatStatisticsAdministratorActionsInfo,
  "chatStatisticsInviterInfo": ChatStatisticsInviterInfo,
  "chatStatisticsSupergroup": ChatStatisticsSupergroup,
  "chatStatisticsChannel": ChatStatisticsChannel,
  "messageStatistics": MessageStatistics,
  "point": Point,
  "vectorPathCommandLine": VectorPathCommandLine,
  "vectorPathCommandCubicBezierCurve": VectorPathCommandCubicBezierCurve,
  "botCommandScopeDefault": BotCommandScopeDefault,
  "botCommandScopeAllPrivateChats": BotCommandScopeAllPrivateChats,
  "botCommandScopeAllGroupChats": BotCommandScopeAllGroupChats,
  "botCommandScopeAllChatAdministrators": BotCommandScopeAllChatAdministrators,
  "botCommandScopeChat": BotCommandScopeChat,
  "botCommandScopeChatAdministrators": BotCommandScopeChatAdministrators,
  "botCommandScopeChatMember": BotCommandScopeChatMember,
  "updateAuthorizationState": UpdateAuthorizationState,
  "updateNewMessage": UpdateNewMessage,
  "updateMessageSendAcknowledged": UpdateMessageSendAcknowledged,
  "updateMessageSendSucceeded": UpdateMessageSendSucceeded,
  "updateMessageSendFailed": UpdateMessageSendFailed,
  "updateMessageContent": UpdateMessageContent,
  "updateMessageEdited": UpdateMessageEdited,
  "updateMessageIsPinned": UpdateMessageIsPinned,
  "updateMessageInteractionInfo": UpdateMessageInteractionInfo,
  "updateMessageContentOpened": UpdateMessageContentOpened,
  "updateMessageMentionRead": UpdateMessageMentionRead,
  "updateMessageLiveLocationViewed": UpdateMessageLiveLocationViewed,
  "updateNewChat": UpdateNewChat,
  "updateChatTitle": UpdateChatTitle,
  "updateChatPhoto": UpdateChatPhoto,
  "updateChatPermissions": UpdateChatPermissions,
  "updateChatLastMessage": UpdateChatLastMessage,
  "updateChatPosition": UpdateChatPosition,
  "updateChatIsMarkedAsUnread": UpdateChatIsMarkedAsUnread,
  "updateChatIsBlocked": UpdateChatIsBlocked,
  "updateChatHasScheduledMessages": UpdateChatHasScheduledMessages,
  "updateChatVoiceChat": UpdateChatVoiceChat,
  "updateChatDefaultDisableNotification": UpdateChatDefaultDisableNotification,
  "updateChatReadInbox": UpdateChatReadInbox,
  "updateChatReadOutbox": UpdateChatReadOutbox,
  "updateChatUnreadMentionCount": UpdateChatUnreadMentionCount,
  "updateChatNotificationSettings": UpdateChatNotificationSettings,
  "updateScopeNotificationSettings": UpdateScopeNotificationSettings,
  "updateChatMessageTtlSetting": UpdateChatMessageTtlSetting,
  "updateChatActionBar": UpdateChatActionBar,
  "updateChatTheme": UpdateChatTheme,
  "updateChatReplyMarkup": UpdateChatReplyMarkup,
  "updateChatDraftMessage": UpdateChatDraftMessage,
  "updateChatFilters": UpdateChatFilters,
  "updateChatOnlineMemberCount": UpdateChatOnlineMemberCount,
  "updateNotification": UpdateNotification,
  "updateNotificationGroup": UpdateNotificationGroup,
  "updateActiveNotifications": UpdateActiveNotifications,
  "updateHavePendingNotifications": UpdateHavePendingNotifications,
  "updateDeleteMessages": UpdateDeleteMessages,
  "updateUserChatAction": UpdateUserChatAction,
  "updateUserStatus": UpdateUserStatus,
  "updateUser": UpdateUser,
  "updateBasicGroup": UpdateBasicGroup,
  "updateSupergroup": UpdateSupergroup,
  "updateSecretChat": UpdateSecretChat,
  "updateUserFullInfo": UpdateUserFullInfo,
  "updateBasicGroupFullInfo": UpdateBasicGroupFullInfo,
  "updateSupergroupFullInfo": UpdateSupergroupFullInfo,
  "updateServiceNotification": UpdateServiceNotification,
  "updateFile": UpdateFile,
  "updateFileGenerationStart": UpdateFileGenerationStart,
  "updateFileGenerationStop": UpdateFileGenerationStop,
  "updateCall": UpdateCall,
  "updateGroupCall": UpdateGroupCall,
  "updateGroupCallParticipant": UpdateGroupCallParticipant,
  "updateNewCallSignalingData": UpdateNewCallSignalingData,
  "updateUserPrivacySettingRules": UpdateUserPrivacySettingRules,
  "updateUnreadMessageCount": UpdateUnreadMessageCount,
  "updateUnreadChatCount": UpdateUnreadChatCount,
  "updateOption": UpdateOption,
  "updateStickerSet": UpdateStickerSet,
  "updateInstalledStickerSets": UpdateInstalledStickerSets,
  "updateTrendingStickerSets": UpdateTrendingStickerSets,
  "updateRecentStickers": UpdateRecentStickers,
  "updateFavoriteStickers": UpdateFavoriteStickers,
  "updateSavedAnimations": UpdateSavedAnimations,
  "updateSelectedBackground": UpdateSelectedBackground,
  "updateChatThemes": UpdateChatThemes,
  "updateLanguagePackStrings": UpdateLanguagePackStrings,
  "updateConnectionState": UpdateConnectionState,
  "updateTermsOfService": UpdateTermsOfService,
  "updateUsersNearby": UpdateUsersNearby,
  "updateDiceEmojis": UpdateDiceEmojis,
  "updateAnimatedEmojiMessageClicked": UpdateAnimatedEmojiMessageClicked,
  "updateAnimationSearchParameters": UpdateAnimationSearchParameters,
  "updateSuggestedActions": UpdateSuggestedActions,
  "updateNewInlineQuery": UpdateNewInlineQuery,
  "updateNewChosenInlineResult": UpdateNewChosenInlineResult,
  "updateNewCallbackQuery": UpdateNewCallbackQuery,
  "updateNewInlineCallbackQuery": UpdateNewInlineCallbackQuery,
  "updateNewShippingQuery": UpdateNewShippingQuery,
  "updateNewPreCheckoutQuery": UpdateNewPreCheckoutQuery,
  "updateNewCustomEvent": UpdateNewCustomEvent,
  "updateNewCustomQuery": UpdateNewCustomQuery,
  "updatePoll": UpdatePoll,
  "updatePollAnswer": UpdatePollAnswer,
  "updateChatMember": UpdateChatMember,
  "updates": Updates,
  "logStreamDefault": LogStreamDefault,
  "logStreamFile": LogStreamFile,
  "logStreamEmpty": LogStreamEmpty,
  "logVerbosityLevel": LogVerbosityLevel,
  "logTags": LogTags,
  "testInt": TestInt,
  "testString": TestString,
  "testBytes": TestBytes,
  "testVectorInt": TestVectorInt,
  "testVectorIntObject": TestVectorIntObject,
  "testVectorString": TestVectorString,
  "testVectorStringObject": TestVectorStringObject,
};
